apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: "25"
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "100"
    spec:
      containers:
        # - image: gcr.io/knative-samples/autoscale-go:0.1
        - image: ghcr.io/ren15/knative_try/python-flask:latest
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"